### PR TITLE
chore: code cleanup for `associative_vector`

### PR DESCRIPTION
**Pull request by tearfur**
This PR gets minor issues out of the way before moving on to actual fixes and improvements.

I've split the changes to single topic commits, so that it is easy to review each of them one by one.

### CODE REVIEW

**Comment by alandefreitas** [comment]
I went though all the commits and they all look great. Is this PR good to go?

**Comment by tearfur** [comment]
Yes, please go ahead.

**Comment by tearfur** [comment]
Hold on a bit for merging, just found a bug in `upper_bound()`.

**Comment by tearfur** [comment]
@alandefreitas Adding new commit e0c55ff for the bug fix, and b3e1af9 for a slight perf improvement. Ready for review again.

**Comment by alandefreitas** [comment]
Mmm... I seems like things broke now.

**Comment by tearfur** [comment]
Oops, made a small typo in the latest commit.

**Comment by tearfur** [comment]
@alandefreitas Anything else needed for this to be merged?

As soon as this is merged, I can submit the next PR, which is based on these changes.

**Comment by alandefreitas** [comment]
No. This looks great. Thanks!

**Pull request merged**
