### PR TITLE
Fixing readme formatting

### PR DESCRIPTION
**Pull request by LehmRob**
Fixing markdown formatting for README file.

### CODE REVIEW

**Comment by alandefreitas** [comment]
We need this mkdocs formatting to indicate [content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#grouping-code-blocks) so the docs look like [this](https://alandefreitas.github.io/small/quickstart/).

A possible solution would be to have one markdown for the docs only and a small README.md containing only a link to the documentation. I'm not sure that's desirable. Maybe it is useful to it make it explicit that the docs are going to look bad on Github.

**Comment by LehmRob** [comment]
Ah okay. I understand. For me it looked like a mix of markdown and reStrucutured text. mkdocs documentation looks pretty good. Does it need to be in the Readme file or can you make documentation in a seperate file. If that's the case, the maybe creating a minimal readme file with a link to your mkdocs page is a better way to solve it.

**Comment by alandefreitas** [comment]
> Does it need to be in the Readme file or can you make documentation in a seperate file. 

It could be in a separate file. 

> If that's the case, the maybe creating a minimal readme file with a link to your mkdocs page is a better way to solve it.

I did consider doing that before. But then I noticed I used the same [tool](https://alandefreitas.github.io/mdsplit/) in this much more influential [repo](https://github.com/alandefreitas/matplotplusplus) (it actually looks worse) and no one ever complained about it. Maybe some people disliked it but never enough to complain. So I just left it as it was. 

But we can still do it. This format might be a little confusing indeed.

**Comment by LehmRob** [comment]
Thanks for the clarification. Maybe I'm the only person, who gets the nervous itching in the neck if I see a rendered document like you readme. :smiley:  Like I said, the mkdocs page looks beatiful and you already have a big link in it for directing the user to this page. So I close the pull request and play around a little bit with mkdocs.

**Comment by alandefreitas** [comment]
For this library, I tried to make the integration section very compact in the documentation to emphasize that it's simple and that people don't need to be scared of dependencies. Unfortunately, about 80% of C++ programmers still use file amalgamation for everything, which doesn't scale well. 

This leads to these nested tabs that look so bad right in the quickstart. So maybe it's more reasonable to split the README.md file in this repository. In any case, we can do that as part of another simpler PR.

Thanks for noticing the problem.

**Pull request closed without merging**
