### PR TITLE
fix: only accept base pointer in `pointer_wrapper` comparison operators

### LINKED ISSUE #31: Using the move constructor of `small::vector` fails to build on FreeBSD
## The problem

If the move constructor of `small::vector` is used, the program will fail to build on FreeBSD.

It could be a problem with the llvm headers, I'm not sure yet.

### Steps to Reproduce

<details>
<summary>CMakeLists.txt</summary>

```cmake
cmake_minimum_required(VERSION 3.22)
project(small_ftbfs)

set(CMAKE_CXX_STANDARD 17)

include(FetchContent)

FetchContent_Declare(small
        GIT_REPOSITORY https://github.com/alandefreitas/small
        GIT_TAG origin/master
)

FetchContent_GetProperties(small)
if(NOT small_POPULATED)
    FetchContent_Populate(small)
    add_subdirectory(${small_SOURCE_DIR} ${small_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()

add_executable(small_ftbfs main.cpp)
target_link_libraries(small_ftbfs PUBLIC small::small)
```

</details>

```c++
#include <iostream>
#include <utility>

#include <small/vector.h>

using Vec = small::max_size_vector<std::pair<int, int>>;

Vec create()
{
    auto ret = Vec{};
    ret.emplace_back(1, 2);
    ret.emplace_back(3, 4);
    return ret;
}

int main()
{
    auto vec = Vec{};
    vec = create();

    for (auto [lhs, rhs] : vec)
    {
        std::cout << lhs << ' ' << rhs << std::endl;
    }

    return 0;
}

```

Note: You need to patch `vector.hpp` with #30 first, or else this problem will get masked by it.

### Output

<details>
 
```console
In file included from /root/small-ftbfs/main.cpp:1:
In file included from /usr/include/c++/v1/iostream:37:
In file included from /usr/include/c++/v1/ios:214:
In file included from /usr/include/c++/v1/__locale:18:
In file included from /usr/include/c++/v1/memory:819:
In file included from /usr/include/c++/v1/__memory/ranges_uninitialized_algorithms.h:22:
/usr/include/c++/v1/__memory/uninitialized_algorithms.h:45:41: error: use of overloaded operator '!=' is ambiguous (with operand types 'small::pointer_wrapper<std::pair<int, int> *>' and 'std::__unreachable_sentinel')
    for (; __ifirst != __ilast && __idx != __olast; ++__ifirst, (void)++__idx)
                                  ~~~~~ ^  ~~~~~~~
/usr/include/c++/v1/__memory/uninitialized_algorithms.h:61:26: note: in instantiation of function template specialization 'std::__uninitialized_copy<std::pair<int, int>, std::move_iterator<small::pointer_wrapper<std::pair<int, int> *>>, std::move_iterator<small::pointer_wrapper<std::pair<int, int> *>>, small::pointer_wrapper<std::pair<int, int> *>, std::__unreachable_sentinel>' requested here
  auto __result = _VSTD::__uninitialized_copy<_ValueType>(_VSTD::move(__ifirst), _VSTD::move(__ilast),
                         ^
/root/small-ftbfs/build_deb/_deps/small-src/source/small/vector.h:241:30: note: in instantiation of function template specialization 'std::uninitialized_copy<std::move_iterator<small::pointer_wrapper<std::pair<int, int> *>>, small::pointer_wrapper<std::pair<int, int> *>>' requested here
                        std::uninitialized_copy(std::make_move_iterator(rhs.begin()),
                             ^
/root/small-ftbfs/main.cpp:13:12: note: in instantiation of member function 'small::vector<std::pair<int, int>, 6, std::allocator<std::pair<int, int>>, std::integral_constant<bool, false>>::vector' requested here
    return ret;
           ^
/usr/include/c++/v1/__memory/uninitialized_algorithms.h:30:55: note: candidate function [with _Iter = small::pointer_wrapper<std::pair<int, int> *>]
  _LIBCPP_HIDE_FROM_ABI friend _LIBCPP_CONSTEXPR bool operator!=(const _Iter&, __unreachable_sentinel) _NOEXCEPT {
                                                      ^
/root/small-ftbfs/build_deb/_deps/small-src/source/small/detail/iterator/pointer_wrapper.h:182:27: note: candidate function [with Iter = std::pair<int, int> *, BaseIter = std::__unreachable_sentinel]
    inline constexpr bool operator!=(const pointer_wrapper<Iter> &x, const BaseIter &y) noexcept {
```
</details>

## Platform

- [ ] *cross-platform issue - linux*
- [ ] *cross-platform issue - windows*
- [ ] *cross-platform issue - macos*
- [x] *other:* FreeBSD 13.2

### Environment Details
 - OS: FreeBSD
 - OS Version: 13.2-RELEASE
 - Compiler: clang included with FreeBSD
 - Compiler version: 14.0.5

### PR DESCRIPTION
**Pull request by tearfur**
Fixes #31.

Tested with the test program in the original issue.

### CODE REVIEW

**Comment by alandefreitas** [comment]
> For the very least, we need to find a way for Pointer to accept both const T* and T* (or something to that effect).

Yes. That's quite limiting. IIRC, we had to extent these operators in the past because they were limiting.

We probably just have to come up with a concept and use SFINAE there.

**Comment by tearfur** [comment]
I already have a solution for this in bea6a7c, see if you are happy with it.

**Comment by alandefreitas** [comment]
That looks reasonable. It would be good to include the case that caused the issue #31 in `test/unit/...` so we don't break that in later versions.

**Comment by tearfur** [comment]
Will do.

**Comment by tearfur** [comment]
@alandefreitas Tests added. PR ready for review.

**Comment by alandefreitas** [comment]
That looks great. Thanks.

**Pull request merged**
